import "../styles/modern-normalize.css";
import "../styles/style.css";
import "../styles/components/header.css";
import "../styles/components/slider.css";
import "../styles/components/hero.css";
import "../styles/components/about.css";
import "../styles/components/gallery.css";
import "../styles/components/contact.css";
import "../styles/utils.css";
