import "../styles/modern-normalize.css";
import "../styles/style.css";
// import "../styles/bootstrap-5.3.3-dist/css/bootstrap.min.css";
import "../styles/components/header.css";
import "../styles/components/slider.css";
import "../styles/components/hero.css";
import "../styles/components/about.css";
import "../styles/components/swiper.css";
import "../styles/components/contact.css";
import "../styles/utils.css";
